# Generated by Django 3.1.2 on 2020-10-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
