# Generated by Django 3.1.2 on 2020-11-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
