# Generated by Django 3.1.2 on 2020-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20201110_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='top_issues',
            field=models.ManyToManyField(to='main_page.Issue'),
        ),
    ]
