language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: FtQRuFFIdH2PXfx8aIfVTgRRpJ7A052u6QOguVENKqAg2jstfGOb04XhoqUhlvjigGX1PY6z8Z0iTeJeNqFTiGVUDGCjFfSqLD53E7CXIXDrAj3u+tV7JqF5tUw3dHLxltts1PKXCuELIw04CJ/I1eVgBQgFJsMgeOBzYMfDNXCya1iZSpNTlNU+xz/rFVJPC4xrLTJz688/y53DeAUwG5WIsJWN3PugMh1v0FklP6xG+5qV+zm3edVqdJsLkhRkNWy8N+O9QYkTbG84sa8WKe0yqxIDu7QruKz+TWaS7/9+BBMCPn9g78R4AtB7VF103gzHuhE1MfvHwcd5aRjw7U5SEE0YRpoMpHl4yODrxHmwD9FHQ46Pc+PgE/heYBv8f5KqHXDvZTVSqpFEOQ9mE96fYroTJdDn4d9u2BTJvOU9dsqfb7X8QvBpq7V2LKPPhYq3KfeJ1CmsKgd6aBfvHKoqlUe2r39LMrTbDsC1q5MOAcnUiNFlJg/ZnEtmkUpK7sqSP1lIsu1B9RrhAn+gxL7wdl2L2VctEgd8Z/HsN3whq7A3yqod/11lti92y+5Ggc7ABhliopu9L/FzFoFQKdA7hm7+D+xpUY2E1Fncc8pcAtgdwVO2jx5Kufd2MHPN/T6DJ77pzOPQ0NghxSpVXkqiyvUlm5QlQuRIYgiRJjg=
  app: civic-connect-group-2-27
  on:
    repo: uva-cs3240-f20/project-2-27
