language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: aqcvM4vcMvg8d3UDqL/RbJXIj2dqJq1/uXDkQNHaritsFbjJe3mAAnYYXE+Drfe/Mmtkep0RFOX2UT5HOTqpLE3Okb+drmlT4VyuNCEHXpuyLr7Qc8nIJSZ9XLoLFRrGiqwagqdCswe1OxsVpMTRJcAyKu98LgKTte/vd2oKhYZ+GoJj4huOlc/p+zwHqHAxTLvYm4bhNWHT5XbXHFSXCO8u5BCQhdEkp5LuSQaHhtNq1/QjZRxXRLrmUxhOkq0+pnpeg62B4o8/ACcSGiL5nHJZaSwcoEgNfWqX2OLRkdMN86i4B/krlrWsq6i1dub+F1oAU3nYDR7LA17/mfWVwvBQrUDTWIwn4EVLJo1Os5paa0CXsK2ChmgKkCBS5RrYA/RSc5Hyg1Aye2PguANInRQjLP+V/0tuy3jmmAkJqp1hgTFWNGwE6PXoj3aVPKhMvszkwT59X5kbse73OdqpA2qfwX1qSrLXg7DZJAJkuFNfYE5c6i8XqvupHZNTYdXTv41W4/4FhP/w4c/IJJ+zwTVLCOqzLTclJ03BrqDfY1vx6q97KhiXqOI1BoF19REWTxN/+xYyerfPr5WD/kpiHIT4UnIwOvUozwxhQt4HmxerXILVMXAFXAWtPczAakEUk9YYotuenFONq9tM9kU+zfMGHqdn6LQC8FhK8ejLMWc=
  app: civic-connect-group-2-27
  on:
    repo: uva-cs3240-f20/project-2-27
