language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: nrXNlTb0v++8isf62VLB2AE+O/evW3AO1uSz1u+gu7icX/FIiUdg1eb2Poz6mbgQxeitRsU9TMfMLNTlQYJjZGxxta54u/zk7mbCb0ybdYvfhpoRnSlmSfL7QBGjlmod73VeCN4RK2DifbWGR9H7is/q6p22lg2Mcr7rvnCruLvWX7PJSNTtsCaeai3nWxbIYfwCaDv6GQVPsin3LvQy+RFjg6eizHI7zJ9Sr2++DDtr/FFNnMxqPZ7atly3wjaM9zknMq+ymkwfuNdjnmLCecjZAJz72E8XNkpjjV1DM+HFz1cL5lo4rmRt6EKxy7P3E6o/l0TE8dXIuy9ze84eHMF866lyqbHDCqB1gRDUvRjc8r2RCQ6Yy9+iz72/LoUoM3ZYZ9qPBukzSB3tJd0MNYc95zgEfsahvhhq9U1dwzW0dtl6/jTFvp9/l4f3R9fnuz3ZHuDdGzPR24O9fLfZJWrbOs/s06uqGTIEPsLmaAye3NXAeAcsjwOceAMIWx1Cmo13lCfkWrCJyRuRifH/pPR448KM1kJME5Xm9V/QdDLrIU/35DqP5G5uwsTTN7T/Nk8pZzzyyuzVIVfjPvsaAH8rDPWyoxHHdtwSOiswXdw85XhlVm7XWZzJK0/1qkeDVUlY4oTDFL8TBy/HIhpEDv3hbwl7lFXbhpIPGI+Tbw8=
  app: civic-connect-group-2-27
  on:
    repo: uva-cs3240-f20/project-2-27
